export const stations = {
  virar: {
    name: "Virar",
    emoji: "🛑",
    barClass: "wr",
    lines: [{ label: "Western Line", tagClass: "ps-line-tag--wr" }],
    desc: "The last stop (or first stop!) on the Western Line. Virar is the northern end of WR — like the starting door of a very long blue road. Many families live here because homes are more affordable.",
    facts: [
      { icon: "📍", text: "District: Palghar (just outside Mumbai)" },
      { icon: "⏱️", text: "~72 min fast train to Churchgate" },
      { icon: "🏡", text: "Popular for affordable housing — suburban living" },
      { icon: "🚂", text: "First train from Virar: ~4:26 AM" },
    ],
  },
  borivali: {
    name: "Borivali",
    emoji: "🌳",
    barClass: "wr",
    lines: [{ label: "Western Line", tagClass: "ps-line-tag--wr" }],
    desc: "Borivali is a big, lively suburb on WR — home to the famous Sanjay Gandhi National Park (a forest inside the city!). It's a major station where many fast trains stop.",
    facts: [
      { icon: "🌿", text: "Sanjay Gandhi National Park is right here — lions, leopards & jungle!" },
      { icon: "🛍️", text: "Borivali market is a huge shopping destination" },
      { icon: "📍", text: "Fast trains stop here — great starting point" },
      { icon: "⏱️", text: "~45 min to Churchgate by fast train" },
    ],
  },
  dahisar: {
    name: "Dahisar",
    emoji: "🔵",
    barClass: "wr",
    lines: [{ label: "Western Line", tagClass: "ps-line-tag--wr" }],
    desc: "Dahisar is where the WR enters the outer suburbs. Metro Line 2A and Metro Line 7 serve this area too, making it a growing interchange zone in north-west Mumbai.",
    facts: [
      { icon: "🚇", text: "Near Metro 2A (Dahisar) and Metro 7 (Dahisar East) terminus" },
      { icon: "🏙️", text: "The boundary between Mumbai and Mira-Bhayandar area" },
      { icon: "📍", text: "Many commuters start journeys here for WR trains" },
    ],
  },
  kandivali: {
    name: "Kandivali",
    emoji: "🏘️",
    barClass: "wr",
    lines: [{ label: "Western Line", tagClass: "ps-line-tag--wr" }],
    desc: "Kandivali is a busy residential suburb on WR, known for its large housing societies and shopping malls. Very popular with middle-class families.",
    facts: [
      { icon: "🛒", text: "Infiniti Mall and various shopping centres nearby" },
      { icon: "🏡", text: "Huge residential population — one of WR's most boarded stations" },
      { icon: "⏱️", text: "~40 min to Churchgate by fast train" },
    ],
  },
  andheri: {
    name: "Andheri",
    emoji: "🔄",
    barClass: "wr",
    lines: [
      { label: "Western Line", tagClass: "ps-line-tag--wr" },
      { label: "Metro Line 1", tagClass: "ps-line-tag--purple" },
      { label: "Metro Line 7", tagClass: "ps-line-tag--orange" },
    ],
    desc: "Andheri is the beating heart of Mumbai's suburbs — a mega-hub where WR local meets Metro Line 1 (east-west) and Metro Line 7. It's also home to Bollywood film studios, the domestic airport (just 3 km away), and the BKC business district nearby.",
    facts: [
      { icon: "✈️", text: "Mumbai domestic airport (Chhatrapati Shivaji International) is 3 km away" },
      { icon: "🎬", text: "Bollywood studios like Film City are in Goregaon nearby" },
      { icon: "🚇", text: "Metro 1 connects Andheri to Ghatkopar in 21 minutes (east-west)" },
      { icon: "💼", text: "Major IT and corporate hub — SEEPZ, Chakala area" },
    ],
  },
  bandra: {
    name: "Bandra",
    emoji: "👑",
    barClass: "wr",
    lines: [{ label: "Western Line", tagClass: "ps-line-tag--wr" }],
    desc: "Bandra is the 'Queen of Suburbs' — Mumbai's coolest neighbourhood with the sea, cafes, celebrities, and the famous Bandra-Worli Sea Link. A favourite stop for everyone.",
    facts: [
      { icon: "🌊", text: "Bandstand promenade and Bandra Fort on the seafront" },
      { icon: "⭐", text: "Celebrity homes — Shah Rukh Khan, Salman Khan live nearby" },
      { icon: "🚆", text: "Bandra Terminus nearby for long-distance trains to Rajasthan & Gujarat" },
      { icon: "☕", text: "Carter Road and Linking Road — top dining and shopping" },
    ],
  },
  dadar: {
    name: "Dadar",
    emoji: "🔄",
    barClass: "gold",
    lines: [
      { label: "Western Line", tagClass: "ps-line-tag--wr" },
      { label: "Central Line", tagClass: "ps-line-tag--cr" },
    ],
    desc: "Dadar is Mumbai's super-interchange. The WR and CR Dadar stations are about 12 minutes walk from each other — this is how you switch between the two main lines without going all the way to Churchgate or CSMT. Also the start point for many south India trains.",
    facts: [
      { icon: "🔄", text: "WR Dadar and CR Dadar: ~12 min walk apart" },
      { icon: "🌸", text: "Dadar flower market — one of Mumbai's most famous markets" },
      { icon: "🚆", text: "Origin point for trains to Goa, Kolhapur, Karnataka" },
      { icon: "📍", text: "Geographic centre of Mumbai — equal distance from north and south" },
    ],
  },
  mumbai_central: {
    name: "Mumbai Central",
    emoji: "🚆",
    barClass: "gold",
    lines: [{ label: "Western Line", tagClass: "ps-line-tag--wr" }],
    desc: "Mumbai Central is the Western Line's long-distance terminus — from here, trains go to Delhi, Ahmedabad, Rajasthan, and beyond. The local WR line also passes through. Two stations in one building.",
    facts: [
      { icon: "🚄", text: "Rajdhani to Delhi, Duronto to Ahmedabad depart from here" },
      { icon: "🏢", text: "Two stations: Mumbai Central (local WR) and Mumbai Central (long distance)" },
      { icon: "📍", text: "Near Tardeo — central south Mumbai location" },
      { icon: "🛍️", text: "Famous for its Bhelpuri and street food outside the station" },
    ],
  },
  churchgate: {
    name: "Churchgate",
    emoji: "⛱️",
    barClass: "wr",
    lines: [{ label: "Western Line", tagClass: "ps-line-tag--wr" }],
    desc: "Churchgate is the southern terminus of Western Line — the last stop on the blue line. It's in the heart of South Mumbai, surrounded by colonial-era buildings, Marine Drive, and the Arabian Sea.",
    facts: [
      { icon: "🌊", text: "Marine Drive (Queen's Necklace) is a 5-minute walk away" },
      { icon: "🏛️", text: "Surrounded by heritage buildings — High Court, University of Mumbai" },
      { icon: "🎯", text: "The WR starts and ends here — zero travel distance" },
      { icon: "🚂", text: "First train from Churchgate: 4:33 AM daily" },
    ],
  },
  kasara: {
    name: "Kasara / Kalyan",
    emoji: "🛑",
    barClass: "cr",
    lines: [{ label: "Central Line", tagClass: "ps-line-tag--cr" }],
    desc: "Kasara is the far northeastern terminus of the Central Line main line. Kalyan is the major hub before the line splits — some trains go to Kasara, others to Khopoli. The gateway to rural Nashik District.",
    facts: [
      { icon: "🏔️", text: "Near the Sahyadri mountain range — scenic hill country" },
      { icon: "🌾", text: "Gateway to rural Maharashtra from Mumbai" },
      { icon: "⏱️", text: "~2 hours from CSMT by fast train" },
      { icon: "📍", text: "Kalyan is a major junction where lines to Kasara and Khopoli split" },
    ],
  },
  thane: {
    name: "Thane",
    emoji: "🏙️",
    barClass: "cr",
    lines: [{ label: "Central Line", tagClass: "ps-line-tag--cr" }],
    desc: "Thane is a major city in its own right — India's City of Lakes. It's the busiest station on the Central Line after CSMT. Thousands of commuters board here daily for Mumbai offices.",
    facts: [
      { icon: "🏞️", text: "Famous for Upvan Lake and many beautiful lakes within the city" },
      { icon: "🏗️", text: "Fastest growing suburb with massive residential development" },
      { icon: "⏱️", text: "~35 min to CSMT by fast train" },
      { icon: "🚌", text: "BEST and TMMT buses connect entire Thane city from here" },
    ],
  },
  ghatkopar: {
    name: "Ghatkopar",
    emoji: "🔄",
    barClass: "purple",
    lines: [
      { label: "Central Line", tagClass: "ps-line-tag--cr" },
      { label: "Metro Line 1", tagClass: "ps-line-tag--purple" },
    ],
    desc: "Ghatkopar is where the Central Line meets Mumbai Metro Line 1 — giving eastern suburb commuters a fast air-conditioned link to Andheri and the western suburbs in just 21 minutes! This changed east Mumbai's commute forever.",
    facts: [
      { icon: "🚇", text: "Metro Line 1 from here to Andheri takes just 21 minutes" },
      { icon: "🔄", text: "The east-west Metro 1 corridor's eastern end" },
      { icon: "🏙️", text: "Major residential and commercial suburb in eastern Mumbai" },
      { icon: "⏱️", text: "~20 min to CSMT by fast train" },
    ],
  },
  kurla: {
    name: "Kurla / LTT",
    emoji: "🚆",
    barClass: "gold",
    lines: [{ label: "Central Line", tagClass: "ps-line-tag--cr" }],
    desc: "Kurla is a mega junction — the local CR trains stop here, and nearby LTT (Lokmanya Tilak Terminus) is the departure point for long-distance trains to UP, Bihar, East India and beyond.",
    facts: [
      { icon: "🚆", text: "LTT (Lokmanya Tilak Terminus) is 1 km from Kurla local station" },
      { icon: "🗺️", text: "Gateway to North and East India — UP, Bihar, Jharkhand trains" },
      { icon: "🚇", text: "Metro Line 3 (Aqua Line) also has a Kurla station nearby" },
      { icon: "🏙️", text: "BKC (Bandra-Kurla Complex) business district is close by" },
    ],
  },
  csmt: {
    name: "CSMT",
    emoji: "🏛️",
    barClass: "cr",
    lines: [
      { label: "Central Line", tagClass: "ps-line-tag--cr" },
      { label: "Harbour Line", tagClass: "ps-line-tag--hl" },
      { label: "Metro Line 3 Aqua", tagClass: "ps-line-tag--aqua" },
    ],
    desc: "CSMT — Chhatrapati Shivaji Maharaj Terminus — is Mumbai's grandest station and a UNESCO World Heritage Site. It's the starting point for Central Line and Harbour Line locals, AND long-distance trains across India. Metro Line 3 also terminates here underground.",
    facts: [
      { icon: "🏛️", text: "UNESCO World Heritage Site — Victorian Gothic architecture built in 1888" },
      { icon: "🚂", text: "Trains to Delhi, Chennai, Kolkata, Hyderabad depart from here" },
      { icon: "🚇", text: "Metro Line 3 (Aqua Line) terminus directly below the station" },
      { icon: "📸", text: "One of the most photographed buildings in Mumbai" },
    ],
  },
  wadala: {
    name: "Wadala",
    emoji: "🌊",
    barClass: "hl",
    lines: [{ label: "Harbour Line", tagClass: "ps-line-tag--hl" }],
    desc: "Wadala is the first major stop after CSMT on the Harbour Line. A rapidly developing area with several infrastructure projects. The Dr. Babasaheb Ambedkar Memorial is located near here.",
    facts: [
      { icon: "🏛️", text: "Near Indu Mills — Dr. Ambedkar Memorial complex" },
      { icon: "🏗️", text: "Major MMRDA development zone — Wadala Truck Terminal becoming residential" },
      { icon: "📍", text: "Eastern waterfront area — near the harbour" },
    ],
  },
  chembur: {
    name: "Chembur",
    emoji: "🏘️",
    barClass: "hl",
    lines: [{ label: "Harbour Line", tagClass: "ps-line-tag--hl" }],
    desc: "Chembur is a well-established suburb on the Harbour Line, known for its residential neighbourhoods and proximity to both Navi Mumbai and south Mumbai via the Eastern Freeway.",
    facts: [
      { icon: "🛣️", text: "Eastern Freeway nearby — direct 20-min road link to CSMT" },
      { icon: "🏡", text: "Popular residential suburb with strong social infrastructure" },
      { icon: "🚇", text: "Metro Line 3 has a Chembur station nearby" },
    ],
  },
  vashi: {
    name: "Vashi",
    emoji: "🏙️",
    barClass: "hl",
    lines: [{ label: "Harbour Line", tagClass: "ps-line-tag--hl" }],
    desc: "Vashi is the gateway to Navi Mumbai — the planned city built to ease Mumbai's congestion. It's a clean, organised city with wide roads, parks, and a massive wholesale market called APMC.",
    facts: [
      { icon: "🥦", text: "APMC Market — Asia's largest wholesale fruit and vegetable market" },
      { icon: "🏙️", text: "Navi Mumbai's busiest commercial and residential node" },
      { icon: "⏱️", text: "~35–40 min from CSMT on Harbour Line" },
      { icon: "🌉", text: "Vashi Bridge connects to Thane and Belapur area" },
    ],
  },
  panvel: {
    name: "Panvel",
    emoji: "🌊",
    barClass: "hl",
    lines: [{ label: "Harbour Line", tagClass: "ps-line-tag--hl" }],
    desc: "Panvel is the southern end of the Harbour Line — and the northern gateway of Konkan Railway. Trains to Goa, Mangalore, and Kerala travel through Panvel. It's also near the under-construction Navi Mumbai International Airport.",
    facts: [
      { icon: "🌊", text: "Konkan Railway's northern gateway — trains to Goa depart from here" },
      { icon: "✈️", text: "Navi Mumbai International Airport (under construction) is nearby" },
      { icon: "⏱️", text: "~65–70 min from CSMT on Harbour Line" },
      { icon: "🏔️", text: "Scenic Sahyadri mountains visible from the city" },
    ],
  },
};
