"""Added column banner_image

Revision ID: 042a74454fa0
Revises: 28df21ab8919
Create Date: 2026-02-03 11:38:01.128312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042a74454fa0'
down_revision = '28df21ab8919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('banner_image')

    # ### end Alembic commands ###
