"""Added highlight column into listing

Revision ID: 1420224a43da
Revises: ab99e7d7b72f
Create Date: 2026-01-31 21:00:23.271096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1420224a43da'
down_revision = 'ab99e7d7b72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('highlight')

    # ### end Alembic commands ###
