"""Added social media links in business

Revision ID: 19208d2c0519
Revises: 042a74454fa0
Create Date: 2026-02-03 17:46:36.637610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19208d2c0519'
down_revision = '042a74454fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_links', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('social_links')

    # ### end Alembic commands ###
