"""Schema Changes

Revision ID: 1eadc8e7f11c
Revises: eb24a6b27183
Create Date: 2026-01-15 11:19:28.235435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1eadc8e7f11c'
down_revision = 'eb24a6b27183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo_alias_slugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('canonical_location_id', sa.Integer(), nullable=False),
    sa.Column('canonical_category_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['canonical_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('logo_image')
        batch_op.drop_column('social_links')
        batch_op.drop_column('average_rating')
        batch_op.drop_column('website_url')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seo_keywords', sa.Text(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_column('image_path')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gallery', sa.JSON(), nullable=True))
        batch_op.create_unique_constraint('uq_business_location', ['business_id', 'location_id'])
        batch_op.drop_column('amenities')
        batch_op.drop_column('featured_image')
        batch_op.drop_column('gallery_images')
        batch_op.drop_column('seo_title')
        batch_op.drop_column('seo_description')
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')
        batch_op.drop_column('price_range')
        batch_op.drop_column('title')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'locations', ['parent_id'], ['id'])
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price_range', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('seo_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('seo_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gallery_images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('featured_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('amenities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_business_location', type_='unique')
        batch_op.drop_column('gallery')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('seo_keywords')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('social_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('logo_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('rating')
        batch_op.drop_column('logo')
        batch_op.drop_column('website')

    op.drop_table('seo_alias_slugs')
    # ### end Alembic commands ###
