"""Added TOC for blog

Revision ID: 218bf48f3990
Revises: b43525bec763
Create Date: 2026-04-05 10:09:58.702337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218bf48f3990'
down_revision = 'b43525bec763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toc', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('toc')

    # ### end Alembic commands ###
