"""Added tranding score column to category

Revision ID: 28d853245bc7
Revises: 5d1ae5273001
Create Date: 2026-01-23 12:39:23.700306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d853245bc7'
down_revision = '5d1ae5273001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_images_business_id'))
        batch_op.drop_constraint(batch_op.f('business_images_business_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trending_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('trending_score')

    with op.batch_alter_table('business_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('business_images_business_id_fkey'), 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_business_images_business_id'), ['business_id'], unique=False)

    # ### end Alembic commands ###
