"""Rename column about into listing

Revision ID: 28df21ab8919
Revises: 1420224a43da
Create Date: 2026-01-31 21:01:26.016029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28df21ab8919'
down_revision = '1420224a43da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.JSON(), nullable=True))
        batch_op.drop_column('highlight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('about')

    # ### end Alembic commands ###
