"""Added map url

Revision ID: 31236a10beee
Revises: 19208d2c0519
Create Date: 2026-02-03 18:02:28.432290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31236a10beee'
down_revision = '19208d2c0519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_map_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('google_map_url')

    # ### end Alembic commands ###
