"""Added fields in location.

Revision ID: 3f56cac6749d
Revises: d977511835cc
Create Date: 2026-03-30 20:59:57.947084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f56cac6749d'
down_revision = 'd977511835cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('population', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('municipal_body', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('location_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('travelling_connectivity', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('living_style', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('nearby_locations', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('best_services', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('food', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('places_to_visit', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('night_life', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('night_life')
        batch_op.drop_column('places_to_visit')
        batch_op.drop_column('food')
        batch_op.drop_column('best_services')
        batch_op.drop_column('nearby_locations')
        batch_op.drop_column('living_style')
        batch_op.drop_column('travelling_connectivity')
        batch_op.drop_column('location_image')
        batch_op.drop_column('municipal_body')
        batch_op.drop_column('population')
        batch_op.drop_column('about')

    # ### end Alembic commands ###
