"""Added hot score column to category

Revision ID: 48959527738f
Revises: 28d853245bc7
Create Date: 2026-01-23 12:40:19.255841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48959527738f'
down_revision = '28d853245bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hot_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('hot_score')

    # ### end Alembic commands ###
