"""Location category mapping change and added realted changes.

Revision ID: 5ad56c777ed7
Revises: 5ba282ae4880
Create Date: 2026-02-23 13:46:03.157310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad56c777ed7'
down_revision = '5ba282ae4880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_category_assets')
    op.create_table('location_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('seo_slug', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'category_id', name='uq_location_category'),
    sa.UniqueConstraint('seo_slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_category_assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('location_category_assets_category_id_fkey')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('location_category_assets_location_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('location_category_assets_pkey')),
    sa.UniqueConstraint('location_id', 'category_id', name=op.f('uq_location_category'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('location_category')
    # ### end Alembic commands ###
