"""Added verification_token_sent_at column to business user.

Revision ID: 5f61dee58bb5
Revises: 0a8926fdc1d9
Create Date: 2026-02-09 20:49:00.125210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f61dee58bb5'
down_revision = '0a8926fdc1d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_users', schema=None) as batch_op:
        batch_op.drop_column('verification_token_sent_at')

    # ### end Alembic commands ###
