"""add emoji and google_places_api_type to category

Revision ID: 87040765ed41
Revises: a5ae9fb920b5
Create Date: 2026-06-11 09:02:27.057635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87040765ed41'
down_revision = 'a5ae9fb920b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emoji', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('google_places_api_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('google_places_api_type')
        batch_op.drop_column('emoji')

    # ### end Alembic commands ###
