"""Blog implementation

Revision ID: 8f42d3d25cc1
Revises: 3f56cac6749d
Create Date: 2026-04-05 09:16:46.114694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f42d3d25cc1'
down_revision = '3f56cac6749d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('featured_image', sa.String(length=255), nullable=True),
    sa.Column('author_name', sa.String(length=120), nullable=True),
    sa.Column('author_bio', sa.Text(), nullable=True),
    sa.Column('author_tagline', sa.String(length=255), nullable=True),
    sa.Column('author_image', sa.String(length=255), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('reading_time', sa.Integer(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs')
    # ### end Alembic commands ###
