"""Added location icon field

Revision ID: 9c52bde2b17b
Revises: 6b3be383b606
Create Date: 2026-04-12 19:42:08.949486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c52bde2b17b'
down_revision = '6b3be383b606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_icon', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('location_icon')

    # ### end Alembic commands ###
