"""Added new fields to user.

Revision ID: b1dfbb8e6dee
Revises: 9c52bde2b17b
Create Date: 2026-04-16 09:05:36.755912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1dfbb8e6dee'
down_revision = '9c52bde2b17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('lname', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone')
        batch_op.drop_column('area')
        batch_op.drop_column('lname')
        batch_op.drop_column('fname')

    # ### end Alembic commands ###
