"""Removed short description

Revision ID: b43525bec763
Revises: f2b3a3632e51
Create Date: 2026-04-05 09:25:49.365995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43525bec763'
down_revision = 'f2b3a3632e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('short_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
