"""add guide section json columns to location

Revision ID: fd533e01241b
Revises: 87040765ed41
Create Date: 2026-06-11 09:59:37.354822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd533e01241b'
down_revision = '87040765ed41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_vibe', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('resident_profile', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('sub_areas', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('property_prices', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('schools', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('hospitals', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('major_employers', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('food_tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('local_events', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('upcoming_projects', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('residential_societies', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('faq', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('civic_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('area_report_card', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('seo_keywords', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('seo_keywords')
        batch_op.drop_column('area_report_card')
        batch_op.drop_column('civic_data')
        batch_op.drop_column('faq')
        batch_op.drop_column('residential_societies')
        batch_op.drop_column('upcoming_projects')
        batch_op.drop_column('local_events')
        batch_op.drop_column('food_tags')
        batch_op.drop_column('major_employers')
        batch_op.drop_column('hospitals')
        batch_op.drop_column('schools')
        batch_op.drop_column('property_prices')
        batch_op.drop_column('sub_areas')
        batch_op.drop_column('resident_profile')
        batch_op.drop_column('character_vibe')

    # ### end Alembic commands ###
